// Code generated by Kitex v0.0.8. DO NOT EDIT.
package helloservice

import (
	"github.com/cloudwego/kitex/server"
	"github.com/go/go-thrift-service/kitex_gen/github/go/go_thrift_service"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler go_thrift_service.HelloService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
